name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t aceest-fitness:ci .

      - name: Run tests inside the built image
        run: docker run --rm aceest-fitness:ci pytest -q